const assert=require('node:assert/strict'),L=require('../core.js');
let count=0;const test=(name,fn)=>{fn();console.log('✓',name);count++;};const near=(a,b)=>assert.equal(L.cents(a),L.cents(b));
function setup(amount=100,repeat=false){const s=L.empty(),c=L.upsertPocket(s,{label:'Aluguel',targetAmount:amount,targetDate:L.dateInMonth(L.planningMonth(s),30),recurrence:repeat?'monthly':'once'});return {s,c};}
function manual(s,c,v=80){L.setManual(s,Object.fromEntries(L.cats(s).map(x=>[x.id,x.id===c.id?v:x.role==='free'?100-v:0])));}
function ledger(s){return JSON.stringify({t:s.transactions,m:s.allocationCategories.map(c=>c.movements),debts:s.debts});}
function checkMoney(s){const q=L.summary(s),deposit=s.allocationCategories.reduce((n,c)=>n+c.movements.filter(m=>['deposit','adjustment'].includes(m.type)).reduce((n,m)=>n+L.cents(m.amount),0),0),spent=s.allocationCategories.reduce((n,c)=>n+c.movements.filter(m=>m.type==='spend').reduce((n,m)=>n+L.cents(m.amount),0),0);assert.equal(L.cents(q.pockets)+L.cents(q.pending),L.cents(q.lifetimeIncome)+deposit-spent);L.validate(s);}
test('Manual: 80 previstos, apenas 20 faltando; 60 de excesso mais 20 livres = 80 em Livre',()=>{const{s,c}=setup();L.move(s,c.id,'deposit',80);manual(s,c);const p=L.allocation(s,100);assert.equal(p.shares[c.id],2000);assert.equal(p.shares.livre,8000);assert.equal(p.overflowCents,6000);L.income(s,{value:100});near(L.pocket(s,c.id),100);near(L.summary(s).free,80);checkMoney(s);});
test('Manual: cofrinho completo fica com 0 efetivo, mesmo com barra salva em 100%',()=>{const{s,c}=setup();L.move(s,c.id,'deposit',100);manual(s,c,100);const settings=JSON.stringify(s.allocation);L.income(s,{value:55.99});near(L.pocket(s,c.id),100);near(L.summary(s).free,55.99);assert.equal(JSON.stringify(s.allocation),settings);});
test('Todas as barras podem continuar sendo arrastadas independentemente; teto não altera configuração',()=>{const{s,c}=setup(1);manual(s,c,99.99);L.income(s,{value:1000});near(L.pocket(s,c.id),1);near(L.summary(s).free,999);assert.equal(s.allocation[c.id],99.99);});
test('Auto: excedente de um plano não é empurrado para outro compromisso',()=>{const{s,c}=setup(10);c.targetDate=L.today();const b=L.upsertPocket(s,{label:'Longo',targetAmount:1000,targetDate:L.afterMonths(360)});const p=L.allocation(s,100);assert.equal(p.shares[c.id],1000);assert(p.shares.livre>8000);assert(p.shares[b.id]<1000);assert.equal(Object.values(p.shares).reduce((a,n)=>a+n,0),10000);});
test('Cofrinho completo no automático segue fora dos próximos aportes',()=>{const{s,c}=setup(1);L.income(s,{value:1});L.income(s,{value:2});near(L.pocket(s,c.id),1);near(L.summary(s).free,2);});
test('Limite funciona sem data e não presume uma meta mensal para planos únicos',()=>{const{s,c}=setup(10);c.targetDate='';manual(s,c,100);L.income(s,{value:15});near(L.pocket(s,c.id),10);near(L.summary(s).free,5);});
test('Distribuir pendências respeita o teto a cada ganho e repetir não duplica',()=>{const{s,c}=setup(20);manual(s,c,100);L.income(s,{value:15,distribute:false});L.income(s,{value:15,distribute:false});const p=L.previewPending(s);assert.equal(p.shares[c.id],2000);assert.equal(p.shares.livre,1000);L.applyPending(s);const old=ledger(s);assert.throws(()=>L.applyPending(s));assert.equal(ledger(s),old);});
test('Aumentar ganho antigo limita apenas o acréscimo e preserva o já separado',()=>{const{s,c}=setup(100);const t=L.income(s,{value:80}).entry;const original=L.contributionCents(t,c.id);L.income(s,{id:t.id,value:200});assert.equal(original,8000);assert.equal(L.contributionCents(t,c.id),10000);assert.equal(L.contributionCents(t,'livre'),10000);checkMoney(s);});
test('Aumentar ganho que já quitou dívida não ressuscita o cofrinho concluído',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Dívida',total:40});const t=L.income(s,{value:40}).entry;L.settleDebt(s,d.id);L.income(s,{id:t.id,value:80});near(L.pocket(s,d.pocketId),0);near(L.summary(s).free,40);assert(L.cat(s,d.pocketId).archived);checkMoney(s);});
test('Reduzir/excluir ganho já usado segue protegido',()=>{const{s,c}=setup();const t=L.income(s,{value:100}).entry;L.move(s,c.id,'spend',80);assert.throws(()=>L.income(s,{id:t.id,value:10}));assert.throws(()=>L.removeIncome(s,t.id));});
test('Transferência de outra reserva respeita teto e leva o excedente a Livre sem novo ganho',()=>{const{s,c}=setup(10);const source=L.upsertPocket(s,{label:'Reserva',targetAmount:200});L.move(s,source.id,'deposit',100);const p=L.move(s,source.id,'transfer',60,{destinationId:c.id});near(L.pocket(s,c.id),10);near(L.pocket(s,source.id),40);near(L.summary(s).free,50);near(L.summary(s).lifetimeIncome,0);assert.equal(p.overflowCents,5000);checkMoney(s);});
test('Transferir de Livre para alvo parcial mantém a sobra na origem, sem lançar ida e volta',()=>{const{s,c}=setup(10);L.move(s,'livre','deposit',100);L.move(s,'livre','transfer',60,{destinationId:c.id});near(L.pocket(s,c.id),10);near(L.summary(s).free,90);assert.equal(L.cat(s,'livre').movements.filter(m=>m.type==='transfer_out').length,1);});
test('Aporte externo também respeita limite; não vira receita fictícia',()=>{const{s,c}=setup(10);L.move(s,c.id,'deposit',30);near(L.pocket(s,c.id),10);near(L.summary(s).free,20);near(L.summary(s).lifetimeIncome,0);checkMoney(s);});
test('Correção para saldo real acima do alvo é preservada, mas bloqueia novos aportes',()=>{const{s,c}=setup(10);L.move(s,c.id,'adjustment',25);manual(s,c,100);L.income(s,{value:10});near(L.pocket(s,c.id),25);near(L.summary(s).free,10);});
test('Retirar de meta única para emergência reabre a necessidade sem alterar renda',()=>{const{s,c}=setup(100);L.income(s,{value:100});L.move(s,c.id,'spend',25);assert.equal(L.target(s,c).remaining,25);L.income(s,{value:50});near(L.pocket(s,c.id),100);near(L.summary(s).free,25);});
test('Livre atravessa a virada: não vira ganho, pendência ou aporte automático',()=>{const{s,c}=setup(100,true);L.income(s,{value:180});const old=ledger(s),month=L.planningMonth(s);L.rollMonth(s,{expectedMonth:month,renewIds:[c.id]});assert.equal(ledger(s),old);near(L.summary(s).free,80);near(L.summary(s).monthIncome,0);assert.equal(s.planning.closures[0].metrics.freeCents,8000);});
test('Redistribuição opcional de Livre usa o mesmo limite e mantém renda/histórico antigos',()=>{const{s,c}=setup(100);L.move(s,'livre','deposit',250);const tx=JSON.stringify(s.transactions),p=L.previewFree(s,200);assert.equal(p.movedCents,10000);assert.equal(p.remainingFreeCents,15000);L.distributeFree(s,200,{expectedSignature:p.signature});near(L.pocket(s,c.id),100);near(L.summary(s).free,150);assert.equal(JSON.stringify(s.transactions),tx);checkMoney(s);});
test('Livre manual não obriga usar tudo: porcentagem livre continua intocada',()=>{const{s,c}=setup(1000);L.move(s,'livre','deposit',100);manual(s,c,60);L.distributeFree(s,100);near(L.pocket(s,c.id),60);near(L.summary(s).free,40);});
test('Livre: plano completo é no-op; saldo insuficiente e confirmação velha são recusados',()=>{const{s,c}=setup(100);L.move(s,'livre','deposit',200);const p=L.previewFree(s,100);L.distributeFree(s,100,{expectedSignature:p.signature});const saved=ledger(s);assert.throws(()=>L.distributeFree(s,100,{expectedSignature:p.signature}));assert.throws(()=>L.distributeFree(s,100));assert.throws(()=>L.previewFree(s,150));assert.equal(ledger(s),saved);});
test('Consumo mensal conta no ciclo: aluguel pago não começa a ser juntado de novo naquele mês',()=>{const{s,c}=setup(100,true);manual(s,c,100);L.income(s,{value:100});L.move(s,c.id,'spend',100);assert(L.target(s,c).done);near(L.target(s,c).used,100);L.income(s,{value:20});near(L.pocket(s,c.id),0);near(L.summary(s).free,20);});
test('Na virada, só o compromisso renovado abre outro ciclo; saldo existente já conta',()=>{const{s,c}=setup(100,true);L.income(s,{value:150});L.move(s,c.id,'spend',60);const month=L.planningMonth(s);L.rollMonth(s,{expectedMonth:month,renewIds:[c.id]});near(L.target(s,c).remaining,60);L.distributeFree(s,50);near(L.pocket(s,c.id),90);near(L.summary(s).lifetimeIncome,150);});
test('Virar mês sem renovar não reabre automaticamente cofrinho mensal já atendido',()=>{const{s,c}=setup(100,true);L.income(s,{value:100});L.move(s,c.id,'spend',100);L.rollMonth(s,{expectedMonth:L.planningMonth(s),renewIds:[]});assert(L.target(s,c).done);L.income(s,{value:50});near(L.summary(s).free,50);});
test('Desfazer virada altera só ciclo/planos, não desfaz redistribuição já confirmada',()=>{const{s,c}=setup(100,true);L.income(s,{value:150});L.move(s,c.id,'spend',100);L.rollMonth(s,{expectedMonth:L.planningMonth(s),renewIds:[c.id]});const id=s.planning.undo.id;L.distributeFree(s,50);const old=ledger(s);L.undoPlanning(s,id);assert.equal(ledger(s),old);assert(L.target(s,c).done);});
test('Dívida: reservar reduz a falta de reserva, não registra um pagamento fictício',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Cartão',total:40});L.income(s,{value:10});const f=L.debtFunding(s,d);near(f.remaining,30);near(f.reserved,10);near(f.balance,40);near(f.paid,0);assert.equal(d.movements.length,0);});
test('Dívida financiada para de receber, mas continua em Organizar até a confirmação',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Cartão',total:40});manual(s,L.cat(s,d.pocketId),100);L.income(s,{value:100});assert(L.debtFunding(s,d).ready);assert(L.cats(s).some(c=>c.id===d.pocketId));near(L.pocket(s,d.pocketId),40);near(L.summary(s).free,60);});
test('Quitei consome reserva UMA vez e tira o cofrinho, mantendo os registros',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Cartão',total:40});manual(s,L.cat(s,d.pocketId),100);L.income(s,{value:100});const p=L.settlementPreview(s,d.id);L.settleDebt(s,d.id,{expectedSignature:p.signature});near(L.debtBalance(s,d),0);near(L.pocket(s,d.pocketId),0);near(L.summary(s).free,60);near(L.summary(s).lifetimeIncome,100);assert(!L.cats(s).some(c=>c.id===d.pocketId));assert.equal(d.movements.filter(m=>m.type==='payment').length,1);assert.equal(s.allocation.livre,100);assert.throws(()=>L.settleDebt(s,d.id));checkMoney(s);});
test('Saldo insuficiente exige confirmação de complemento, sem fazer reserva ficar negativa',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Cartão',total:40});L.income(s,{value:10});const old=ledger(s);assert.throws(()=>L.settleDebt(s,d.id));assert.equal(ledger(s),old);const p=L.settleDebt(s,d.id,{allowExternal:true});near(p.external,30);near(L.pocket(s,d.pocketId),0);near(L.debtPaid(d),40);checkMoney(s);});
test('Pagar uma parte reduz a dívida e a reserva, conservando o que falta reservar',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Cartão',total:100});L.income(s,{value:40});L.payDebt(s,d.id,20);const f=L.debtFunding(s,d);near(f.remaining,60);near(f.reserved,20);near(f.paid,20);near(f.balance,80);assert(!L.cat(s,d.pocketId).archived);});
test('Pagar dívida com outra origem devolve eventual sobra da reserva original a Livre',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Cartão',total:40});L.income(s,{value:40});L.settleDebt(s,d.id,{sourceId:'',allowExternal:true});near(L.summary(s).free,40);near(L.pocket(s,d.pocketId),0);assert(L.cat(s,d.pocketId).archived);checkMoney(s);});
test('Duas dívidas em cofrinho legado nunca reutilizam a mesma reserva',()=>{let s=L.empty();s.allocationCategories.push({id:'old-debt',label:'Dívidas',role:'debt',color:'#bb819c',icon:'💳',movements:[]});s.debts=[{id:'a',name:'Primeira',pocketId:'old-debt',initialTotal:100,due:'2026-10-01',movements:[]},{id:'b',name:'Segunda',pocketId:'old-debt',initialTotal:100,due:'2026-11-01',movements:[]}];s=L.normalize(s);L.move(s,'old-debt','deposit',150);near(L.debtFunding(s,'a').reserved,100);near(L.debtFunding(s,'b').reserved,50);near(L.debtFunding(s,'b').remaining,50);L.settleDebt(s,'a');assert(!L.cat(s,'old-debt').archived);near(L.pocket(s,'old-debt'),50);near(L.debtFunding(s,'b').reserved,50);});
test('Quitar uma dívida compartilhada por último conclui a reserva; reabrir dívida não duplica cofrinho',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Cartão',total:40});L.income(s,{value:40});L.settleDebt(s,d.id);assert.throws(()=>L.restorePocket(s,d.pocketId));L.upsertDebt(s,{id:d.id,name:d.name,total:10});assert(!L.cat(s,d.pocketId).archived);assert.equal(s.allocationCategories.filter(c=>c.id===d.pocketId).length,1);near(L.debtFunding(s,d).remaining,10);});
test('Saldo antigo acima do limite não é confiscado na atualização',()=>{const{s,c}=setup(10);L.move(s,c.id,'adjustment',50);s.version=11;const old=ledger(s),next=L.normalize(s);assert.equal(ledger(next),old);assert.deepEqual(L.normalize(next),next);manual(next,L.cat(next,c.id),100);L.income(next,{value:10});near(L.pocket(next,c.id),50);near(L.summary(next).free,10);});
test('Centavos e 800 aportes/transferências mistos: saldo geral sempre se conserva',()=>{const{s,c}=setup(75.37);manual(s,c,73.21);for(let i=0;i<800;i++){L.income(s,{value:(i%17+1)/100});if(i%23===0&&L.summary(s).free>0){const p=L.previewFree(s,L.summary(s).free);if(p.movedCents)L.distributeFree(s,L.summary(s).free);}assert(L.pocket(s,c.id)<=75.37);checkMoney(s);}});

function asV23(s){const raw=L.clone(s);raw.version=11;for(const c of raw.allocationCategories)delete c.cycleSpentBaselineCents;if(raw.planning.undo){for(const c of raw.planning.undo.before.categories)delete c.cycleSpentBaselineCents;const expected=JSON.parse(raw.planning.undo.expected);for(const c of expected.categories)delete c.cycleSpentBaselineCents;raw.planning.undo.expected=JSON.stringify(expected);}return raw;}
test('Migração v23: virada com desfazer mantém assinatura válida e restaura o ciclo anterior',()=>{const{s,c}=setup(100,true);L.income(s,{value:120});L.move(s,c.id,'spend',100);L.rollMonth(s,{expectedMonth:L.planningMonth(s),renewIds:[c.id]});const raw=asV23(s),next=L.normalize(raw),old=ledger(next);assert(L.canUndoPlanning(next));L.undoPlanning(next,next.planning.undo.id);assert(L.target(next,L.cat(next,c.id)).done);assert.equal(ledger(next),old);});
test('Migração v23: assinatura obsoleta não permite sobrescrever edição posterior',()=>{const{s,c}=setup(100,true);L.rollMonth(s,{expectedMonth:L.planningMonth(s),renewIds:[c.id]});const raw=asV23(s);L.cat(raw,c.id).targetAmount=500;const next=L.normalize(raw);assert(!L.canUndoPlanning(next));assert.throws(()=>L.undoPlanning(next,next.planning.undo.id));});
test('Origem arquivada não pode financiar pagamentos diretos ou quitação',()=>{const s=L.empty(),d=L.upsertDebt(s,{name:'Cartão',total:40}),c=L.upsertPocket(s,{label:'Fonte',targetAmount:100});L.move(s,c.id,'deposit',50);c.archived=true;const old=ledger(s);assert.throws(()=>L.payDebt(s,d.id,20,{sourceId:c.id}));assert.throws(()=>L.settleDebt(s,d.id,{sourceId:c.id}));assert.equal(ledger(s),old);});
console.log(`\n${count} testes de limites, Livre e quitação concluídos.`);
