const assert=require('node:assert/strict');const L=require('../core.js');let count=0;
const test=(title,fn)=>{fn();console.log('✓',title);count++;};
const near=(a,b)=>assert.equal(L.cents(a),L.cents(b));
function fixture(){const s=L.empty();s.profile.name='Teste';s.goals.monthly=1500;s.goals.weekly=300;
 const due=L.dateInMonth(s.planning.month,30);
 const a=L.upsertPocket(s,{label:'Aluguel',targetAmount:400,targetDate:due,recurrence:'monthly'});
 const b=L.upsertPocket(s,{label:'Luz',targetAmount:30,targetDate:due});
 const g=L.upsertPocket(s,{label:'Viagem',targetAmount:1000,targetDate:L.afterMonths(360),role:'goal'});
 const d=L.upsertDebt(s,{name:'Cartão',total:40,due});
 L.income(s,{value:100});L.income(s,{value:25,distribute:false});L.move(s,a.id,'spend',10);
 L.payDebt(s,d.id,2);return {s,a,b,g,d};}
function financial(s){return JSON.stringify({transactions:s.transactions,debts:s.debts,profile:s.profile,movements:s.allocationCategories.map(c=>({id:c.id,m:c.movements})),summary:{income:L.summary(s).lifetimeIncome,balance:L.summary(s).pockets,pending:L.summary(s).pending,debt:L.summary(s).debts}});}
const roll=(s,renewIds=[])=>L.rollMonth(s,{expectedMonth:L.planningMonth(s),expectedSignature:L.planSignature(s),renewIds});

test('Experiência vazia: nenhum registro de virada ou reinício nasce pronto',()=>{const s=L.empty();assert.deepEqual(s.planning.closures,[]);assert.deepEqual(s.planning.resets,[]);assert.equal(s.planning.undo,null);assert.equal(L.resetPlanPreview(s).canReset,false);near(L.summary(s).pockets,0);});
test('Recomeçar não toca em perfil, moeda, ganhos, saldos, pagamentos ou dívidas',()=>{const {s,d}=fixture();s.preferences.currency='CNY';const before=financial(s),due=d.due;L.resetPlanning(s);assert.equal(financial(s),before);assert.equal(s.preferences.currency,'CNY');assert.equal(d.due,due);assert.equal(s.goals.monthly,0);assert.equal(s.goals.weekly,0);assert.equal(s.preferences.allocationMode,'auto');assert.equal(L.forecast(s).hasTargets,false);assert.equal(s.planning.resets.length,1);});
test('Após reinício, próximo ganho fica a separar e nenhum cofrinho recebe escondido',()=>{const{s}=fixture();L.resetPlanning(s);const b=L.summary(s).pockets,p=L.pendingCents(s);L.income(s,{value:100});near(L.summary(s).pockets,b);assert.equal(L.pendingCents(s),p+10000);});
test('Novo plano volta a distribuir sem reaplicar dinheiro histórico',()=>{const{s,a}=fixture();L.resetPlanning(s);const before=L.pocket(s,a.id),snapshot=JSON.stringify(s.transactions);L.upsertPocket(s,{id:a.id,label:a.label,targetAmount:400,targetDate:L.afterMonths(1)});L.income(s,{value:5});near(L.pocket(s,a.id),before+5);assert.equal(JSON.stringify(s.transactions.slice(0,-1)),snapshot);});
test('Dívida continua pagável durante pausa; editar o plano da dívida a reativa',()=>{const{s,d}=fixture();L.resetPlanning(s);const b=L.debtBalance(s,d);L.payDebt(s,d.id,1);near(L.debtBalance(s,d),b-1);assert.equal(L.target(s,L.cat(s,d.pocketId)).amount,0);L.upsertDebt(s,{id:d.id,name:d.name,total:b-1,due:d.due});near(L.target(s,L.cat(s,d.pocketId)).amount,b-1);});
test('Desfazer reinício restaura apenas planos, inclusive referência e divisão manual',()=>{const{s,a}=fixture();const v=Object.fromEntries(L.cats(s).map(c=>[c.id,0]));v[a.id]=80;v.livre=20;L.setManual(s,v);const before=L.planSignature(s);L.resetPlanning(s);const id=s.planning.undo.id;L.income(s,{value:10,distribute:false});const b=financial(s);L.undoPlanning(s,id);assert.equal(L.planSignature(s),before);assert.equal(financial(s),b);assert.equal(s.planning.resets[0].status,'undone');});
test('Desfazer nunca sobrescreve uma edição de planejamento posterior',()=>{const{s,a}=fixture();L.resetPlanning(s);const id=s.planning.undo.id;L.upsertPocket(s,{id:a.id,label:'Novo aluguel',targetAmount:500});const before=JSON.stringify(s);assert.equal(L.canUndoPlanning(s),false);assert.throws(()=>L.undoPlanning(s,id));assert.equal(JSON.stringify(s),before);});
test('Normalização/reabertura preserva a possibilidade de desfazer',()=>{const{s}=fixture();L.resetPlanning(s);const next=L.normalize(JSON.parse(JSON.stringify(s)));assert(L.canUndoPlanning(next));L.undoPlanning(next,next.planning.undo.id);assert(L.forecast(next).hasTargets);assert.deepEqual(L.normalize(next),next);});
test('Reinício é confirmado: assinatura desatualizada recusa sem mutação',()=>{const{s}=fixture(),sig=L.planSignature(s);L.upsertPocket(s,{label:'Outro',targetAmount:20});const raw=JSON.stringify(s);assert.throws(()=>L.resetPlanning(s,{expectedSignature:sig}));assert.equal(JSON.stringify(s),raw);});
test('Virada mantém toda a história financeira; novo mês é filtro, não apagamento',()=>{const{s,a,g,d}=fixture(),before=financial(s),old=L.planningMonth(s),goalDate=g.targetDate,debtDate=d.due;const record=roll(s,[a.id]);assert.equal(financial(s),before);assert.equal(L.planningMonth(s),L.nextMonth(old));assert.equal(g.targetDate,goalDate);assert.equal(d.due,debtDate);near(L.summary(s).monthIncome,0);near(L.summary(s,old+'-01').monthIncome,125);assert.equal(record.metrics.incomeCents,12500);assert.equal(record.metrics.debtPaidCents,200);});
test('Somente itens marcados renovam e nenhum vira uma despesa ou pagamento',()=>{const{s,a,b}=fixture(),old=b.targetDate;const before=JSON.stringify(s.allocationCategories.map(c=>c.movements));roll(s,[a.id]);assert.notEqual(a.targetDate,old);assert.equal(b.targetDate,old);assert.equal(JSON.stringify(s.allocationCategories.map(c=>c.movements)),before);});
test('Renovar não limpa saldo acumulado nem financia novamente o valor já separado',()=>{const s=L.empty();const a=L.upsertPocket(s,{label:'Aluguel',targetAmount:100,targetDate:L.dateInMonth(L.planningMonth(s),30),recurrence:'monthly'});L.income(s,{value:100});roll(s,[a.id]);near(L.pocket(s,a.id),100);L.income(s,{value:50});near(L.pocket(s,a.id),100);near(L.summary(s).free,50);L.move(s,a.id,'spend',100);L.income(s,{value:20});near(L.pocket(s,a.id),0);near(L.summary(s).free,70);assert(L.target(s,a).done);});
test('Dia 31: fevereiro fica no último dia e março volta a 31',()=>{const s=L.empty();s.planning.month='2024-01';const a=L.upsertPocket(s,{label:'Casa',targetAmount:100,targetDate:'2024-01-31',recurrence:'monthly'});L.rollMonth(s,{expectedMonth:'2024-01',renewIds:[a.id],at:'2024-01-31'});assert.equal(a.targetDate,'2024-02-29');L.rollMonth(s,{expectedMonth:'2024-02',renewIds:[a.id],at:'2024-02-29'});assert.equal(a.targetDate,'2024-03-31');assert.equal(L.dateInMonth('2025-02',31),'2025-02-28');});
test('Dezembro vira janeiro sem trocar prazos plurianuais',()=>{const s=L.empty();s.planning.month='2025-12';const a=L.upsertPocket(s,{label:'Casa',targetAmount:100,targetDate:'2025-12-31',recurrence:'monthly'}),g=L.upsertPocket(s,{label:'Plano 30 anos',role:'goal',targetAmount:5000,targetDate:'2055-12-31'});L.rollMonth(s,{expectedMonth:'2025-12',renewIds:[a.id],at:'2025-12-31'});assert.equal(a.targetDate,'2026-01-31');assert.equal(g.targetDate,'2055-12-31');assert.equal(s.planning.month,'2026-01');});
test('Mesmo pedido duas vezes não vira dois meses nem duplica fechamento',()=>{const{s,a}=fixture(),month=s.planning.month;L.rollMonth(s,{expectedMonth:month,renewIds:[a.id]});const after=JSON.stringify(s);assert.throws(()=>L.rollMonth(s,{expectedMonth:month,renewIds:[a.id]}));assert.equal(JSON.stringify(s),after);assert.equal(s.planning.closures.length,1);});
test('Não avança inadvertidamente vários meses futuros',()=>{const{s}=fixture();roll(s);const after=JSON.stringify(s);assert.throws(()=>roll(s));assert.equal(JSON.stringify(s),after);});
test('Não seleciona dívidas, metas plurianuais ou arquivados para renovar',()=>{const{s,g,d}=fixture(),raw=JSON.stringify(s);assert.throws(()=>roll(s,[g.id]));assert.throws(()=>roll(s,[d.pocketId]));assert.equal(JSON.stringify(s),raw);});
test('Desfazer virada mantém uso feito depois e recupera datas/mês anteriores',()=>{const{s,a}=fixture(),plan=L.planSignature(s);roll(s,[a.id]);const id=s.planning.undo.id;L.move(s,a.id,'spend',1);const b=financial(s);L.undoPlanning(s,id);assert.equal(L.planSignature(s),plan);assert.equal(financial(s),b);assert.equal(s.planning.closures[0].status,'undone');roll(s,[a.id]);assert.equal(s.planning.closures.length,2);});
test('Fotografia do fechamento não se altera ao editar um ganho antigo',()=>{const{s,a}=fixture();roll(s,[a.id]);const r=JSON.stringify(s.planning.closures[0]);L.income(s,{id:s.transactions[0].id,value:110,date:s.transactions[0].date});assert.equal(JSON.stringify(s.planning.closures[0]),r);assert.equal(L.monthMetrics(s,s.planning.closures[0].month).incomeCents,13500);});
test('Estado v22 migra sem mudar IDs, contas, rateios e saldos; segunda leitura estável',()=>{const{s}=fixture();delete s.planning;s.version=10;for(const c of s.allocationCategories){delete c.planningPaused;delete c.recurrence;delete c.recurrenceDay;}const b=financial(s),next=L.normalize(s);assert.equal(financial(next),b);assert.equal(next.version,12);assert.deepEqual(L.normalize(next),next);});
test('Meta financeira legada não ressuscita depois de reset/reabertura',()=>{let s=L.empty();s.goals.financial={id:'financial-main',name:'Antiga',target:1000,targetDate:'2050-01-01',initialSaved:5,movements:[]};s=L.normalize(s);L.resetPlanning(s);const next=L.normalize(s);assert(!L.forecast(next).hasTargets);near(L.summary(next).pockets,5);assert(L.canUndoPlanning(next));L.undoPlanning(next,next.planning.undo.id);assert(L.forecast(next).hasTargets);});
test('Repetição sem data é recusada e prazo longo comum nunca vira mensal por inferência',()=>{const s=L.empty();assert.throws(()=>L.upsertPocket(s,{label:'Aluguel',targetAmount:500,recurrence:'monthly'}));const c=L.upsertPocket(s,{label:'Casa',targetAmount:5000,targetDate:L.afterMonths(360)});assert.equal(c.recurrence,'once');assert.equal(L.rolloverPreview(s).candidates.length,0);});
test('Editar só o valor em fevereiro mantém a âncora do vencimento em 31',()=>{const s=L.empty();s.planning.month='2025-01';const a=L.upsertPocket(s,{label:'Aluguel',targetAmount:100,targetDate:'2025-01-31',recurrence:'monthly'});L.rollMonth(s,{expectedMonth:'2025-01',renewIds:[a.id],at:'2025-01-31'});L.upsertPocket(s,{id:a.id,label:a.label,targetAmount:120,targetDate:a.targetDate,recurrence:'monthly'});L.rollMonth(s,{expectedMonth:'2025-02',renewIds:[a.id],at:'2025-02-28'});assert.equal(a.targetDate,'2025-03-31');});
console.log(`\n${count} testes de planejamento e virada concluídos.`);
