/* Storage integration tests: real Node WebCrypto, deterministic in-memory browser adapters.
 * These do NOT claim to exercise an actual mobile IndexedDB implementation. */
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const {webcrypto}=require('node:crypto');const LL=require('../core.js');
const source=fs.readFileSync(path.join(__dirname,'../storage.js'),'utf8');
function memory(){return {local:new Map(),database:new Map(),failLocal:false,failIDB:false,tail:Promise.resolve()};}
function instance(m=memory()){
 const localStorage={getItem:k=>m.local.get(k)||null,setItem:(k,v)=>{if(m.failLocal)throw Error('quota');m.local.set(k,String(v));},removeItem:k=>m.local.delete(k)};
 const indexedDB={open(){const r={};setImmediate(()=>{if(m.failIDB){r.error=Error('idb failed');r.onerror?.();return;}r.result={objectStoreNames:{contains:()=>true},createObjectStore(){},close(){},transaction(){const t={error:null};t.objectStore=()=>({get(k){const q={};setImmediate(()=>{q.result=structuredClone(m.database.get(k));q.onsuccess?.();});return q;},put(value,k){setImmediate(()=>{if(m.failIDB){t.error=Error('idb failed');t.onerror?.();}else{m.database.set(k,structuredClone(value));t.oncomplete?.();}});}});return t;}};r.onsuccess?.();});return r;}};
 const navigator={locks:{request:(_name,fn)=>{const q=m.tail.catch(()=>{}).then(fn);m.tail=q;return q;}}};
 const context=vm.createContext({LL,crypto:webcrypto,localStorage,indexedDB,navigator,TextEncoder,TextDecoder,Uint8Array,atob,btoa,structuredClone,console,setTimeout,clearTimeout});vm.runInContext(source,context);
 return {S:context.LLStore,m};
}
const b64=b=>Buffer.from(b).toString('base64');
async function legacy(m,password){
 const authSalt=webcrypto.getRandomValues(new Uint8Array(16)),dataSalt=webcrypto.getRandomValues(new Uint8Array(16));
 const base=await webcrypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits','deriveKey']);
 const h=await webcrypto.subtle.deriveBits({name:'PBKDF2',salt:authSalt,iterations:250000,hash:'SHA-256'},base,256);
 const key=await webcrypto.subtle.deriveKey({name:'PBKDF2',salt:dataSalt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);
 const raw={version:8,profile:{name:'Nome de teste'},preferences:{currency:'EUR'},allocationCategories:[{id:'casa',label:'Casa',role:'custom',color:'#d5839b',icon:'🏠',targetAmount:400,targetDate:LL.afterMonths(1),movements:[]},{id:'livre',label:'Livre',role:'free',movements:[]}],allocation:{casa:35,livre:65},transactions:[{id:'old-entry',value:100,date:LL.today(),allocationSnapshot:{casa:{pct:35},livre:{pct:65}}}],debts:[],activity:[],goals:{monthly:0,weekly:0,financial:{target:0,movements:[]}}};
 const iv=webcrypto.getRandomValues(new Uint8Array(12)),data=await webcrypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(raw)));
 const envelope={format:'life-lately-encrypted-v1',version:1,iv:b64(iv),data:b64(data)};
 const account={version:1,username:'Nome de teste',usernameNorm:'nome de teste',authSalt:b64(authSalt),authHash:b64(h),dataSalt:b64(dataSalt),createdAt:new Date().toISOString()};
 m.local.set('lifeLatelyZeroV22Account',JSON.stringify(account));m.local.set('lifeLatelyZeroV22State',JSON.stringify(envelope));m.database.set('state',envelope);return {account,envelope};
}
let count=0;const test=async(name,fn)=>{await fn();console.log('✓',name);count++;};
(async()=>{
 await test('Conta nova: senha não aparece em texto puro; dados criptografados',async()=>{const{S,m}=instance();const s=await S.create('Teste QA','Senha-de-teste-2026');assert.equal(s.profile.name,'Teste QA');assert.equal(s.transactions.length,0);const disk=JSON.stringify([...m.local]);assert(!disk.includes('Senha-de-teste-2026'));assert(!disk.includes('"transactions"'));await S.lock();await assert.rejects(()=>S.unlock('senha-errada'));assert.equal((await S.unlock('Senha-de-teste-2026')).profile.name,'Teste QA');});
 await test('Cadastro e envelope v1 antigos abrem sem perder 35/65 ou a moeda',async()=>{const m=memory();await legacy(m,'antiga6');const{S}=instance(m);const s=await S.unlock('antiga6');assert.equal(LL.pocket(s,'casa'),35);assert.equal(LL.pocket(s,'livre'),65);assert.equal(s.preferences.currency,'EUR');await S.save(s);await S.lock();const again=await instance(m).S.unlock('antiga6');assert.equal(LL.summary(again).pockets,100);assert.equal(again.transactions.length,1);});
 await test('Fila de gravação: a última alteração não é perdida',async()=>{const{S,m}=instance();const s=await S.create('Teste','password-test');s.profile.name='A';const a=S.save(s);s.profile.name='B';const b=S.save(s);await Promise.all([a,b]);assert.equal((await instance(m).S.unlock('password-test')).profile.name,'B');});
 await test('Falha só no localStorage ainda salva pelo IndexedDB',async()=>{const{S,m}=instance();const s=await S.create('Teste','password-test');m.failLocal=true;s.profile.name='Ainda salva';await S.save(s);assert.equal((await instance(m).S.unlock('password-test')).profile.name,'Ainda salva');});
 await test('Falha só no IndexedDB ainda salva pelo localStorage',async()=>{const{S,m}=instance();const s=await S.create('Teste','password-test');m.failIDB=true;s.profile.name='Fallback';await S.save(s);assert.equal((await instance(m).S.unlock('password-test')).profile.name,'Fallback');});
 await test('Falha nos dois armazenamentos é reportada, sem falso sucesso',async()=>{const{S,m}=instance();const s=await S.create('Teste','password-test');m.failLocal=m.failIDB=true;await assert.rejects(()=>S.save(s),/salvar/);});
 await test('Duas abas: revisão antiga não sobrescreve a revisão mais recente',async()=>{const{S,m}=instance();const s=await S.create('Teste','password-test');const other=instance(m).S,old=await other.unlock('password-test');s.profile.name='Atualizado';await S.save(s);old.profile.name='Obsoleto';await assert.rejects(()=>other.save(old),/outra aba/);assert.equal((await instance(m).S.unlock('password-test')).profile.name,'Atualizado');});
 await test('Backup v2 restaura cadastro, senha e centavos em outro aparelho',async()=>{const{S}=instance();const s=await S.create('Teste','password-test');LL.upsertPocket(s,{label:'Aluguel',targetAmount:400,targetDate:LL.afterMonths(1)});LL.income(s,{value:123.45});const backup=await S.backup(s),other=instance().S;const prepared=await other.inspectBackup(JSON.stringify(backup),'password-test');await other.restore(prepared);await other.lock();const opened=await other.unlock('password-test');assert.equal(LL.summary(opened).pockets,123.45);assert.equal(opened.profile.name,'Teste');await assert.rejects(()=>other.inspectBackup(JSON.stringify(backup),'errada'));});
 await test('Backup v1 abre na instalação original, não finge portabilidade',async()=>{const m=memory(),original=await legacy(m,'antiga6'),{S}=instance(m);const v1=JSON.stringify({app:'Life Lately',format:'encrypted-backup-v1',payload:original.envelope});assert.equal((await S.inspectBackup(v1,'antiga6')).state.transactions.length,1);await assert.rejects(()=>instance().S.inspectBackup(v1,'antiga6'),/antigo/);});
 await test('Cifra alterada e arquivo estranho são recusados',async()=>{const{S}=instance();const s=await S.create('Teste','password-test'),b=await S.backup(s);b.payload.data='AAAA'+b.payload.data.slice(4);await assert.rejects(()=>S.inspectBackup(JSON.stringify(b),'password-test'));await assert.rejects(()=>S.inspectBackup('{"transactions":[]}','password-test'));});
 await test('Bloqueio tira a chave da memória e impede novas gravações',async()=>{const{S}=instance();const s=await S.create('Teste','password-test');await S.lock();assert.equal(S.isUnlocked(),false);await assert.rejects(()=>S.save(s),/Desbloqueie/);});
 await test('Novo cadastro não apaga dados órfãos nem uma conta existente',async()=>{const m=memory();m.database.set('state',{unrelated:'old'});await assert.rejects(()=>instance(m).S.create('Teste','password-test'),/anteriores/);const{S}=instance();await S.create('Teste','password-test');await assert.rejects(()=>S.create('Outra','password-test'),/existe/);});
 await test('Virada criptografada e backup preservam histórico, saldos e desfazer em outro aparelho',async()=>{const{S}=instance();const s=await S.create('Teste','password-test');const c=LL.upsertPocket(s,{label:'Aluguel',targetAmount:400,targetDate:LL.dateInMonth(LL.planningMonth(s),30),recurrence:'monthly'});LL.income(s,{value:100});const before=LL.planningMonth(s);LL.rollMonth(s,{expectedMonth:before,renewIds:[c.id]});const bk=await S.backup(s);const other=instance().S;const prepared=await other.inspectBackup(JSON.stringify(bk),'password-test');await other.restore(prepared);await other.lock();const opened=await other.unlock('password-test');assert.equal(opened.planning.closures.length,1);assert(LL.canUndoPlanning(opened));assert.equal(LL.summary(opened).pockets,100);LL.undoPlanning(opened,opened.planning.undo.id);await other.save(opened);assert.equal(opened.planning.month,before);assert.equal(LL.summary(opened).pockets,100);});
 await test('Reinício salvo não ressuscita planos ao desbloquear; desfazer restaura só planejamento',async()=>{const{S,m}=instance();const s=await S.create('Teste','password-test');LL.upsertPocket(s,{label:'Viagem',role:'goal',targetAmount:500,targetDate:LL.afterMonths(360)});LL.income(s,{value:15.73});LL.resetPlanning(s);await S.save(s);await S.lock();const other=instance(m).S;const opened=await other.unlock('password-test');assert(!LL.forecast(opened).hasTargets);assert.equal(LL.summary(opened).pockets,15.73);assert(LL.canUndoPlanning(opened));LL.undoPlanning(opened,opened.planning.undo.id);await other.save(opened);assert(LL.forecast(opened).hasTargets);assert.equal(LL.summary(opened).pockets,15.73);});

 await test('v24: backup/reabertura preservam ciclo pago, quitação, sobra Livre e limites',async()=>{const{S,m}=instance();const s=await S.create('Teste v24','password-v24');const c=LL.upsertPocket(s,{label:'Aluguel',targetAmount:100,targetDate:LL.dateInMonth(LL.planningMonth(s),30),recurrence:'monthly'}),d=LL.upsertDebt(s,{name:'Cartão',total:40,due:c.targetDate});LL.income(s,{value:200});LL.settleDebt(s,d.id);LL.move(s,c.id,'spend',100);await S.save(s);await S.lock();const other=instance(m).S,opened=await other.unlock('password-v24');assert(LL.target(opened,LL.cat(opened,c.id)).done);assert(LL.cat(opened,d.pocketId).archived);assert.equal(LL.summary(opened).free,60);LL.rollMonth(opened,{expectedMonth:LL.planningMonth(opened),renewIds:[c.id]});LL.distributeFree(opened,60);const backup=await other.backup(opened),newStore=instance().S;await newStore.restore(await newStore.inspectBackup(JSON.stringify(backup),'password-v24'));await newStore.lock();const restored=await newStore.unlock('password-v24');assert.equal(LL.target(restored,LL.cat(restored,c.id)).remaining,40);assert.equal(LL.pocket(restored,c.id),60);assert.equal(LL.summary(restored).free,0);assert.equal(LL.summary(restored).lifetimeIncome,200);assert(LL.debtFunding(restored,d.id).settled);assert.equal(restored.planning.closures[0].metrics.freeCents,6000);});
 console.log(`\n${count} testes de armazenamento concluídos.`);
})().catch(e=>{console.error(e);process.exit(1);});
