/* Checks for the fresh edition. WebCrypto is real; browser I/O is emulated. */
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const {webcrypto}=require('node:crypto'),LL=require('../core.js');
const source=fs.readFileSync(path.join(__dirname,'../storage.js'),'utf8');
function memory(){return {local:new Map(),dbs:new Map(),locks:new Map(),failDelete:false};}
function instance(m=memory(),legacy=false){
 const localStorage={getItem:k=>m.local.get(k)||null,setItem:(k,v)=>m.local.set(k,String(v)),removeItem:k=>m.local.delete(k)};
 const indexedDB={open(name){let data=m.dbs.get(name);const isNew=!data;if(!data){data=new Map();m.dbs.set(name,data);}const r={};setImmediate(()=>{r.result={objectStoreNames:{contains:()=>true},createObjectStore(){},close(){},transaction(){const t={error:null};t.objectStore=()=>({get(k){const q={};setImmediate(()=>{q.result=structuredClone(data.get(k));q.onsuccess?.();});return q;},put(v,k){setImmediate(()=>{data.set(k,structuredClone(v));t.oncomplete?.();});},delete(k){setImmediate(()=>{if(m.failDelete){t.error=Error('blocked delete');t.onerror?.();}else{data.delete(k);t.oncomplete?.();}});}});return t;}};if(isNew)r.onupgradeneeded?.();r.onsuccess?.();});return r;}};
 const navigator={locks:{request:(name,fn)=>{const q=(m.locks.get(name)||Promise.resolve()).catch(()=>{}).then(fn);m.locks.set(name,q);return q;}}};
 let code=source;
 if(legacy)code=code.replaceAll('lifeLatelyZeroV22Account','lifeLatelyAccountEmptyPreviewV2').replaceAll('lifeLatelyZeroV22State','lifeLatelyStateEmptyPreviewV1').replaceAll("DB_NAME='life-lately-zero-v22'","DB_NAME='life-lately-db-empty-preview-v1'");
 const context=vm.createContext({LL,crypto:webcrypto,localStorage,indexedDB,navigator,TextEncoder,TextDecoder,Uint8Array,atob,btoa,structuredClone,console,setTimeout,clearTimeout});vm.runInContext(code,context);
 return {S:context.LLStore,m};
}
let checks=0;async function test(name,fn){await fn();checks++;console.log('✓',name);}
function assertEmpty(s){assert.equal(s.transactions.length,0);assert.equal(s.debts.length,0);assert.equal(s.activity.length,0);assert.equal(s.goals.monthly,0);assert.equal(s.goals.weekly,0);assert.equal(s.goals.financial.target,0);assert.equal(s.allocationCategories.length,1);assert.equal(s.allocationCategories[0].role,'free');assert.equal(s.allocationCategories[0].targetAmount,0);assert.equal(s.allocationCategories[0].movements.length,0);assert.equal(LL.forecast(s).daily,0);assert.equal(LL.summary(s).lifetimeIncome,0);assert.equal(LL.summary(s).pockets,0);}
(async()=>{
 await test('O estado inicial não contém perfil, meta financeira, dívidas ou ganhos',async()=>{const s=LL.empty();assert.equal(s.profile.name,'');assertEmpty(s);});
 await test('Conta e plano antigos são ignorados, mesmo na mesma origem',async()=>{const m=memory(),old=instance(m,true).S;const s=await old.create('Perfil antigo','password-old');s.goals.monthly=62000;LL.upsertPocket(s,{label:'Plano antigo',targetAmount:62000});await old.save(s);const S=instance(m).S;assert.equal(S.readAccount(),null);const current=await S.create('Acesso novo','password-new');assertEmpty(current);assert.equal(current.profile.name,'Acesso novo');assert.equal((await old.unlock('password-old')).goals.monthly,62000);});
 await test('Gravação posterior ao primeiro acesso persiste sem limpar a cada abertura',async()=>{const{S,m}=instance();const s=await S.create('Novo','password-new');LL.upsertPocket(s,{label:'Aluguel',targetAmount:400,targetDate:LL.afterMonths(1)});LL.income(s,{value:100});await S.save(s);await S.lock();const reopened=await instance(m).S.unlock('password-new');assert.equal(LL.summary(reopened).lifetimeIncome,100);assert.equal(LL.summary(reopened).pockets,100);});
 await test('Recomeçar apaga cadastro, estado espelhado, IndexedDB e chave da memória',async()=>{const{S,m}=instance();const s=await S.create('Novo','password-new');LL.upsertPocket(s,{label:'Teste',targetAmount:100});LL.income(s,{value:30});await S.save(s);await S.erase();assert.equal(S.readAccount(),null);assert.equal(S.isUnlocked(),false);assert.equal(m.local.get(S.keys.ACCOUNT_KEY),undefined);assert.equal(m.local.get(S.keys.FALLBACK),undefined);assert.equal(m.dbs.get(S.keys.DB_NAME).has('state'),false);});
 await test('Depois da limpeza, é possível criar outra conta totalmente vazia',async()=>{const{S}=instance();await S.create('Primeiro','password-one');await S.erase();const s=await S.create('Segundo','password-two');assertEmpty(s);assert.equal(s.profile.name,'Segundo');await S.lock();await assert.rejects(()=>S.unlock('password-one'));assert.equal((await S.unlock('password-two')).profile.name,'Segundo');});
 await test('Não limpa outras chaves nem o banco da edição anterior',async()=>{const m=memory();m.local.set('OtherApp','untouched');const old=instance(m,true).S;const a=await old.create('Anterior','password-old');a.goals.monthly=62000;await old.save(a);const S=instance(m).S;await S.create('Atual','password-new');await S.erase();assert.equal(m.local.get('OtherApp'),'untouched');assert.equal((await old.unlock('password-old')).goals.monthly,62000);});
 await test('Reset exige acesso desbloqueado',async()=>{const{S}=instance();await S.create('Novo','password-new');await S.lock();await assert.rejects(()=>S.erase(),/Desbloqueie/);assert.equal((await S.unlock('password-new')).profile.name,'Novo');});
 await test('Falha na exclusão não informa sucesso nem perde o cadastro',async()=>{const{S,m}=instance();await S.create('Novo','password-new');m.failDelete=true;await assert.rejects(()=>S.erase(),/limpeza/);assert(S.readAccount());m.failDelete=false;await S.lock();assertEmpty(await S.unlock('password-new'));});
 await test('Uma aba antiga não consegue restaurar valores depois do reset',async()=>{const{S,m}=instance();await S.create('Novo','password-new');const other=instance(m).S,old=await other.unlock('password-new');await S.erase();old.goals.monthly=62000;await assert.rejects(()=>other.save(old),/outra aba/);assert.equal(S.readAccount(),null);});
 await test('Formato de backup continua restaurável apenas por ação explícita',async()=>{const{S}=instance();const s=await S.create('Novo','password-new');LL.upsertPocket(s,{label:'Meu plano',targetAmount:400});LL.income(s,{value:100});const text=JSON.stringify(await S.backup(s));await S.erase();assertEmpty(await S.create('Zero','password-zero'));const prepared=await S.inspectBackup(text,'password-new');await S.restore(prepared);await S.lock();assert.equal(LL.summary(await S.unlock('password-new')).lifetimeIncome,100);});
 console.log(`\n${checks} testes de primeiro acesso e reset concluídos.`);
})().catch(err=>{console.error(err);process.exit(1);});
