-- Dedicated AbacatePay billing for Life Lately.
-- Provider credentials remain in Edge Function secrets and never enter Postgres
-- migrations, the public client, or the Osyra project.

create table private.payment_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_code text not null check (product_code ~ '^[a-z0-9][a-z0-9_-]{1,63}$'),
  provider text not null default 'abacatepay' check (provider = 'abacatepay'),
  provider_checkout_id text,
  external_id text not null,
  status text not null default 'pending'
    check (status in ('pending', 'checkout_created', 'paid', 'refunded', 'disputed', 'lost', 'failed', 'canceled', 'expired')),
  amount_cents integer not null check (amount_cents > 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  dev_mode boolean not null,
  checkout_url text,
  payment_method text check (payment_method is null or payment_method in ('PIX', 'CARD')),
  receipt_url text,
  last_error text,
  provider_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(provider_payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  refunded_at timestamptz,
  unique (provider, external_id),
  unique (provider, provider_checkout_id)
);

comment on table private.payment_orders is
  'Server-only Life Lately payment orders. AbacatePay and Osyra data are never shared.';

create index payment_orders_user_product_created_idx
  on private.payment_orders (user_id, product_code, created_at desc);
create index payment_orders_open_idx
  on private.payment_orders (status, updated_at)
  where status in ('pending', 'checkout_created');

alter table private.payment_events
  add column order_id bigint references private.payment_orders(id) on delete set null,
  add column processing_error text;

create index payment_events_order_id_idx
  on private.payment_events (order_id)
  where order_id is not null;

alter table private.payment_orders enable row level security;
alter table private.payment_orders force row level security;
revoke all on table private.payment_orders from public, anon, authenticated;
revoke all on sequence private.payment_orders_id_seq from public, anon, authenticated;

create policy "payment_orders_deny_clients"
on private.payment_orders
for all
to anon, authenticated
using (false)
with check (false);

comment on table public.entitlements is
  'Server-managed Life Lately access status. Authenticated users can read only their own row.';

-- Existing pre-payment testers keep access and cannot be locked out by this release.
insert into public.entitlements (user_id, product_code, status, provider)
select user_id, 'life-lately-lifetime', 'active', 'founder'
from public.profiles
on conflict (user_id, product_code) do nothing;

create or replace function public.billing_prepare_checkout(
  p_user_id uuid,
  p_product_code text,
  p_amount_cents integer,
  p_currency text,
  p_dev_mode boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_order private.payment_orders%rowtype;
begin
  if p_user_id is null or p_product_code <> 'life-lately-lifetime'
     or p_amount_cents <> 2990 or p_currency <> 'BRL' then
    raise exception 'invalid billing product' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  select * into selected_order
  from private.payment_orders
  where user_id = p_user_id
    and product_code = p_product_code
    and provider = 'abacatepay'
    and dev_mode = p_dev_mode
    and status in ('pending', 'checkout_created')
    and updated_at >= now() - interval '20 minutes'
  order by id desc
  limit 1
  for update;

  if selected_order.id is null then
    insert into private.payment_orders (
      user_id,
      product_code,
      external_id,
      amount_cents,
      currency,
      dev_mode
    ) values (
      p_user_id,
      p_product_code,
      'll_' || replace(gen_random_uuid()::text, '-', ''),
      p_amount_cents,
      p_currency,
      p_dev_mode
    )
    returning * into selected_order;
  end if;

  return jsonb_build_object(
    'id', selected_order.id,
    'externalId', selected_order.external_id,
    'status', selected_order.status,
    'checkoutUrl', selected_order.checkout_url,
    'providerCheckoutId', selected_order.provider_checkout_id,
    'devMode', selected_order.dev_mode
  );
end;
$$;

create or replace function public.billing_store_checkout(
  p_order_id bigint,
  p_provider_checkout_id text,
  p_checkout_url text,
  p_provider_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  saved private.payment_orders%rowtype;
begin
  if p_provider_checkout_id is null or btrim(p_provider_checkout_id) = ''
     or p_checkout_url !~ '^https://app[.]abacatepay[.]com/'
     or jsonb_typeof(p_provider_payload) <> 'object' then
    raise exception 'invalid checkout response' using errcode = '22023';
  end if;

  update private.payment_orders
  set provider_checkout_id = p_provider_checkout_id,
      checkout_url = p_checkout_url,
      status = 'checkout_created',
      last_error = null,
      provider_payload = p_provider_payload,
      updated_at = now()
  where id = p_order_id
    and provider = 'abacatepay'
    and status in ('pending', 'checkout_created')
  returning * into saved;

  if saved.id is null then
    raise exception 'payment order not available' using errcode = 'P0002';
  end if;

  return jsonb_build_object(
    'id', saved.id,
    'externalId', saved.external_id,
    'status', saved.status,
    'checkoutUrl', saved.checkout_url,
    'providerCheckoutId', saved.provider_checkout_id,
    'devMode', saved.dev_mode
  );
end;
$$;

create or replace function public.billing_record_checkout_error(
  p_order_id bigint,
  p_error text
)
returns void
language sql
security definer
set search_path = ''
as $$
  update private.payment_orders
  set last_error = left(coalesce(p_error, 'provider error'), 500),
      updated_at = now()
  where id = p_order_id
    and status in ('pending', 'checkout_created');
$$;

create or replace function public.billing_process_payment_event(
  p_provider_event_id text,
  p_event_type text,
  p_external_id text,
  p_provider_checkout_id text,
  p_checkout_status text,
  p_amount_cents integer,
  p_paid_amount_cents integer,
  p_payment_method text,
  p_receipt_url text,
  p_dev_mode boolean,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_order private.payment_orders%rowtype;
  prior_processed_at timestamptz;
  inserted_event boolean;
  target_status text;
begin
  if p_provider_event_id is null or btrim(p_provider_event_id) = ''
     or p_event_type not in ('checkout.completed', 'checkout.refunded', 'checkout.disputed', 'checkout.lost')
     or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'invalid payment event' using errcode = '22023';
  end if;

  insert into private.payment_events (
    provider,
    provider_event_id,
    event_type,
    payload
  ) values (
    'abacatepay',
    p_provider_event_id,
    p_event_type,
    p_payload
  )
  on conflict (provider, provider_event_id) do nothing;
  inserted_event := found;

  if not inserted_event then
    select processed_at into prior_processed_at
    from private.payment_events
    where provider = 'abacatepay'
      and provider_event_id = p_provider_event_id;

    if prior_processed_at is not null then
      return jsonb_build_object('processed', true, 'duplicate', true);
    end if;

    update private.payment_events
    set event_type = p_event_type,
        payload = p_payload,
        received_at = now(),
        processing_error = null
    where provider = 'abacatepay'
      and provider_event_id = p_provider_event_id;
  end if;

  select * into target_order
  from private.payment_orders
  where provider = 'abacatepay'
    and external_id = p_external_id
  limit 1
  for update;

  if target_order.id is null and p_provider_checkout_id is not null then
    select * into target_order
    from private.payment_orders
    where provider = 'abacatepay'
      and provider_checkout_id = p_provider_checkout_id
    limit 1
    for update;
  end if;

  if target_order.id is null then
    update private.payment_events
    set processing_error = 'payment order not found'
    where provider = 'abacatepay' and provider_event_id = p_provider_event_id;
    return jsonb_build_object('processed', false, 'error', 'order_not_found');
  end if;

  if target_order.dev_mode <> p_dev_mode
     or (target_order.provider_checkout_id is not null and target_order.provider_checkout_id <> p_provider_checkout_id)
     or target_order.amount_cents <> p_amount_cents then
    update private.payment_events
    set order_id = target_order.id,
        processing_error = 'checkout identity or amount mismatch'
    where provider = 'abacatepay' and provider_event_id = p_provider_event_id;
    return jsonb_build_object('processed', false, 'error', 'checkout_mismatch');
  end if;

  if p_event_type = 'checkout.completed' then
    if p_checkout_status <> 'PAID' or p_paid_amount_cents <> target_order.amount_cents then
      update private.payment_events
      set order_id = target_order.id,
          processing_error = 'completed checkout is not fully paid'
      where provider = 'abacatepay' and provider_event_id = p_provider_event_id;
      return jsonb_build_object('processed', false, 'error', 'payment_not_complete');
    end if;

    update private.payment_orders
    set status = 'paid',
        provider_checkout_id = coalesce(provider_checkout_id, p_provider_checkout_id),
        payment_method = case when p_payment_method in ('PIX', 'CARD') then p_payment_method else null end,
        receipt_url = p_receipt_url,
        provider_payload = p_payload,
        last_error = null,
        paid_at = coalesce(paid_at, now()),
        updated_at = now()
    where id = target_order.id;

    insert into public.entitlements (
      user_id,
      product_code,
      status,
      provider,
      current_period_end,
      updated_at
    ) values (
      target_order.user_id,
      target_order.product_code,
      'active',
      'abacatepay',
      null,
      now()
    )
    on conflict (user_id, product_code) do update
      set status = 'active',
          provider = 'abacatepay',
          current_period_end = null,
          updated_at = now();
    target_status := 'paid';
  else
    target_status := case p_event_type
      when 'checkout.refunded' then 'refunded'
      when 'checkout.disputed' then 'disputed'
      else 'lost'
    end;

    update private.payment_orders
    set status = target_status,
        provider_payload = p_payload,
        receipt_url = coalesce(p_receipt_url, receipt_url),
        refunded_at = case when p_event_type = 'checkout.refunded' then coalesce(refunded_at, now()) else refunded_at end,
        updated_at = now()
    where id = target_order.id;

    update public.entitlements
    set status = 'canceled',
        provider = 'abacatepay',
        updated_at = now()
    where user_id = target_order.user_id
      and product_code = target_order.product_code;
  end if;

  update private.payment_events
  set order_id = target_order.id,
      processed_at = now(),
      processing_error = null
  where provider = 'abacatepay'
    and provider_event_id = p_provider_event_id;

  return jsonb_build_object(
    'processed', true,
    'duplicate', false,
    'orderId', target_order.id,
    'status', target_status
  );
end;
$$;

revoke all on function public.billing_prepare_checkout(uuid, text, integer, text, boolean) from public, anon, authenticated;
revoke all on function public.billing_store_checkout(bigint, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.billing_record_checkout_error(bigint, text) from public, anon, authenticated;
revoke all on function public.billing_process_payment_event(text, text, text, text, text, integer, integer, text, text, boolean, jsonb) from public, anon, authenticated;

grant execute on function public.billing_prepare_checkout(uuid, text, integer, text, boolean) to service_role;
grant execute on function public.billing_store_checkout(bigint, text, text, jsonb) to service_role;
grant execute on function public.billing_record_checkout_error(bigint, text) to service_role;
grant execute on function public.billing_process_payment_event(text, text, text, text, text, integer, integer, text, text, boolean, jsonb) to service_role;
